name: 'Create deployment on GitHub'
branding:
  icon: shopping-bag
  colour: green
description: 'Sends a request to GitHub in order to track deployment'
inputs:
  environment:
    description: 'Deployment environment'
    deprecationMessage: 'This action is now deprecated. See https://github.com/Shopify/github-deployment-action?tab=readme-ov-file#deprecation-notice for more information.'
    required: true
  preview_url:
    description: 'Preview URL'
  description:
    description: 'Deployment description'
    default: ''
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node20'
  main: 'index.js'
